version: '3.8'
services:
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    container_name: mysql-cron-backup
    volumes:
      - ${VOLUME_PATH}/backup/database:/backup
    networks:
      - ac-network
    environment:
      - MYSQL_HOST=${DB_HOST:-host}
      - MYSQL_USER=${DB_ROOT_USER:-root}
      - MYSQL_PASS=${DB_ROOT_PASSWORD:-password}
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - MYSQL_DATABASE=acore_characters_custom acore_auth_custom acore_world_custom proxy_web web_custom
      # Every day at 10:15
      - CRON_TIME=15 10 * * *
      # Make it small
      - GZIP_LEVEL=6
      - TIMEOUT=60s
    restart: unless-stopped
  
networks:
  ac-network:
    external:
      name: ac-network